version: '3'
services:

  db-etl:
    container_name: db-etl
    build: db
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pg-data-1it-etl:/var/lib/postgresql/data
#    expose:
#      - "5432"
    ports:
      - "15432:5432"
    restart: always

  metabase:
    image: metabase/metabase:v0.45.1
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - metabase-data:/metabase
    restart: always

volumes:
  pg-data-1it-etl:
  metabase-data:
